version: "3.8"

name: warpaint-sound-prod
services:
  ui:
    depends_on:
      - db
      - api
    build:
      context: ./frontend
      dockerfile: ./Dockerfile.prod
      args:
        - REACT_APP_RECAPTCHA_SITE_KEY=$RECAPTCHA_SITE_KEY # react env vars must start with REACT_APP_
        - REACT_APP_BACKEND_URL=$BACKEND_URL
    container_name: wpsound_frontend_prod
    env_file: ./.env
    ports:
      - 3050:80
    working_dir: /app/frontend
    volumes:
      - ./frontend:/app/frontend
    environment:
      - REACT_APP_RECAPTCHA_SITE_KEY=$RECAPTCHA_SITE_KEY # react env vars must start with REACT_APP_
      - REACT_APP_BACKEND_URL=$BACKEND_URL
  api:
    depends_on:
      - db
    build:
      context: ./backend
      dockerfile: ./Dockerfile.prod
    container_name: wpsound_backend_prod
    env_file: ./.env
    ports:
      - 8002:8002
    working_dir: /app/backend
    volumes:
      - ./backend:/app/backend
    environment:
      - DB_HOST=wpsound_db_prod
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASSWORD
      - DB_NAME=$DB_NAME
      - DB_PORT=$DB_PORT
      - DB_DIALECT=postgres
      - TOKEN_KEY=$TOKEN_KEY
      - WARPAINTVISION_GMAIL_EMAIL=$WARPAINTVISION_GMAIL_EMAIL
      - WARPAINTVISION_GMAIL_PASSWORD=$WARPAINTVISION_GMAIL_PASSWORD
  db:
    image: postgres
    container_name: wpsound_db_prod
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_DB=$DB_NAME
  pgadmin:
    depends_on:
      - db
      - api
      - ui
    container_name: wpsound_pgadmin4_prod
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=$PGADMIN_EMAIL
      - PGADMIN_DEFAULT_PASSWORD=$PGADMIN_PASSWORD
    ports:
      - '5051:80'
volumes:
  db-data:

  # docker-compose -f docker-compose.prod.yml build --no-cache
  # docker-compose -f docker-compose.prod.yml up -d
  # docker-compose -f <docker_compose_file> -p "<project_name>" up -d
  # -d (in the backgound - won't fill the terminal other than names)
