version: "3.8"

services:
  ui:
    depends_on:
      - db
      - api
    build: ./frontend
    container_name: wpsound_frontend
    restart: always
    ports:
      - 3001:3000
    working_dir: /app/frontend
    volumes:
      - ./frontend:/app/frontend
    environment:
      - WATCHPACK_POLLING=true # replaced: - CHOKIDAR_USEPOLLING=true / to check changes in react
      - WDS_SOCKET_PORT=$WDS_SOCKET_PORT
      # https://github.com/facebook/create-react-app/issues/10253 
      # https://stackoverflow.com/questions/70488471/docker-with-create-react-app-is-not-updating-changes
  api:
    depends_on:
      - db
    build: ./backend
    container_name: wpsound_backend
    restart: always
    env_file: ./.env
    ports:
      - 8002:8002
    working_dir: /app/backend
    volumes:
      - ./backend:/app/backend
    environment:
      - DB_HOST=wpsound_db
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASSWORD
      - DB_NAME=$DB_NAME
      - DB_PORT=$DB_PORT
      - DB_DIALECT=postgres
      - TOKEN_KEY=$TOKEN_KEY
  db:
    image: postgres
    container_name: wpsound_db
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_DB=$DB_NAME
  pgadmin:
    container_name: wpsound_pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=$PGADMIN_EMAIL
      - PGADMIN_DEFAULT_PASSWORD=$PGADMIN_PASSWORD
    ports:
      - '5051:80'
volumes:
  db-data:
